ci:
  autofix_prs: false
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [end-of-file-fixer, equirements-txt-fixer]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [
            --install-types,
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --ignore-missing-imports,
            --non-interactive,
            # --no-namespace-packages,
            --namespace-packages,
          ]
        additional_dependencies:
          - "pydantic>=2.7.1,<3"
          - "types-protobuf"

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args:
          - -s
          # Skip B113 request_without_timeout because it has false positives e.g. when
          # timeout is computed by a function.
          - B101,B311,B324,B108,B104,B310,B405,B314,B608,B113
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args:
          - --ignore-init-method
          - --ignore-init-module
          - -p
          - -vv
          - olmoearth_projects
          - --fail-under=80

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
